server:
  port: ${APP_PORT:8081}

spring:
  profiles:
    active: default
  application:
    name: service-provider
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
#    url: jdbc:mysql://localhost:3306/boen_qms
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1 
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # 开发环境使用，生产环境建议改为 none
    show-sql: true
  h2:
    console:
      enabled: false    
  sql:
    init:
      mode: always # 开发环境使用，生产环境建议改为 never
      data-locations: classpath:data/mysql.sql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
    banner: false

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: info, health
        exclude: health

info:
  app:
    name: "@project.name@"
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

logging:
  level:
    '[com.zaxxer.hikari]': DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui